### ISSUE TITLE
Change settings in inverter

### ISSUE THREAD

**Issue by Tooltim73** [heszegi/com.heszi.deye#3]
Hello, Thanks for your great app. I was wondering if there is a way to control  the inverter, as in change any setting so i can choose in homey to switch on/off the Grid Charge in a specific time period (time of use) because so i can charge the battery when there is no sun predicted for the next day.

thanks

**Comment by heszegi** [comment]
Hello Tooltip73, thank you! I'm glad to hear the app is helpful to others besides me. Yes, updating the app to include editing settings available through the DeyeCloud API is on the roadmap. However, I can't provide an estimate for when that update will be released just yet. But I'm working on it.

**Comment by Tooltim73** [comment]
Thanks that would be perfect
