### ISSUE TITLE
Missing feature 

### ISSUE THREAD

**Issue by Botje1987** [heszegi/com.heszi.deye#4]
Nice App Lots of information
Only missing few things.

Is not ot showend in the energy app as consumption and usage energy on the energy platform . 
Missing the messing option when grid is missing 

hoop if it is possible to make these things possible 

yours sincerely 

Leon Bot

**Comment by heszegi** [comment]
Hi Leon,

Thank you for your ideas, these are great features.

Could you explain a bit more about how you want this device to be integrated into the energy platform? I'm not very familiar with that part of Homey, so I'm having a hard time imagining how to implement it.

As for the grid status, it's currently not supported by the Deye API. However, they told to plan to add new features in the future, so we're hopeful it will be included.

**Comment by bbrodnik** [comment]
I'm very gratefull for this application.

If possible, I woud welcome two features I miss very muuch:

1. Reading and enabling/disabling Peak Shaving option. It significantly changes selling first mode functionality of inverter, so possibibility of changing this option would help very much in optimizing battery charge/discharge functionality in selling first mode.

2. Grid missing information would enable to react in glid blackout events to notify users and disable unnessesary loads if battery goes too low. And also to manage thing when grid comes back.

Regards,
Brane

**Comment by heszegi** [comment]
Hi @bbrodnik, thank you for your message! Your ideas are great. Unfortunately, the 'Peak Shaving' option isn’t supported by the Deye API, so we can’t implement it until they add that functionality—hopefully, they will. As for the Grid Availability feature, it’s also not currently supported by the API, but I’m testing a solution that might enable it. Hopefully, it’ll be available soon in the Homey app.

**Comment by heszegi** [comment]
App v1.2.0 available with Grid availability function for testing https://homey.app/a/com.heszi.deye/test/

**Comment by bbrodnik** [comment]
Great, I tested and it works well, both #4 and #6.

 

Thank, you,

Brane
